### PR TITLE
Tidier methods for `prais`

### PR DESCRIPTION
**Pull request by skvrnami**
I implemented tidiers - `tidy` and `glance` methods so that the output of `prais_winsten` function can be processed by `modelsummary` and `gtsummary` packages for preparing a publishable output from the results (related to issue/solves #13 ). 

E.g. like this:

```
library(prais)
library(wooldridge)
data("barium")

pw <- prais_winsten(lchnimp ~ lchempi + lgas + lrtwex + befile6 + affile6 + afdec6,
                    data = barium, index = "t")

modelsummary::modelsummary(pw)

gtsummary::tbl_regression(pw)
```

During the implementation, I followed the process suggested here: https://www.tidymodels.org/learn/develop/broom/ and https://modelsummary.com/articles/modelsummary.html#adding-new-models-part-ii. 

Hope it helps.

### CODE REVIEW

**Comment by franzmohr** [comment]
Looks great, thank you very much! 

Would you like to add your contact information (including ORCID) as a "contributor" to the description file?

**Comment by skvrnami** [comment]
> Looks great, thank you very much!
> 
> Would you like to add your contact information (including ORCID) as a "contributor" to the description file?

Yes, please. I updated `DESCRIPTION` with my info. I will leave bumping the version etc. to you. Thanks!

**Comment by rganly** [comment]
Hi, have these updates been implemented into the latest version of the prais package? Thank you.

**Comment by franzmohr** [comment]
@rganly: On it. Should go on CRAN this week.
@skvrnami: Thanks again and apologies for the delay.

**Comment by franzmohr** [comment]
@rganly: The development version on GitHub is updated. Could you please check if it does what you want?

**Pull request merged**
